### ISSUE TITLE
Serverlist is not correct

### ISSUE THREAD

**Issue by VEX-Ben** [overload-development-community/olproxy.otl.gg#14]
There are a few probs with the list. 
It shows the VEX-Server only 1 hour, but our server is running most time and everyone can join or start a game. But the server is not highlighted, only if I stop the server it is highlighted again (!!).
There is no autostart, so I set no timelimit and no one see the server after 1 hour.

Also the DF.net server isn't online, it was a test that not worked, but the server is always in the list.
There must be a way to see what server is realy online or not.

(please excuse my english, hope you understand the probs)

VEX-Ben

**Comment by roncli** [comment]
I set the DF.net server to invisible.  Make sure to have `signOff` set to true in the appsettings.json file on any server you want to have de-listed from the list when the server is shut down.  See https://olproxy.otl.gg/download for details.

As for the VEX-Server, new games *should* cause it to go back in the white.  Greyed out servers are simply servers where active games aren't being played.  If this isn't the behavior you're seeing, let me know and I'll look into it.

I'm in the middle of a pretty big rewrite of the tracker, and am hoping to soon get better with determining whether a server is online or not.

**Comment by VEX-Ben** [comment]
Hi roncli,
thanks for help with the DF.net-Server.

The VEX-Server is most of the time online and everyone can start a game, (not yet 24/7 maybe in future). But the server is only highlighted for 1h after we started the server (no matter if we just started the game „service“ or also joined to actually start a map). 

- means: if I start the server (not a game) it is white, but no map is running and noone can join. But anyone is able to start a map (but who knows this? Can this be shown in the Tracker?).
Also if I start a map without timelimit, it is only 1h white in the tracker, but in the second hour noone can see it as running. 
There is no difference between "server is running" and "map is running". If I restart the server the list shows the server white again. Also when you restart the server you get old status data shown, like a map or/and players on it, although it is now running without a map.

But the biggest issue is if I end the server(!). 
excample:
The server is running but more than an hour, so it's not white anymore, and you now stop the server, it will be white (highlighted) again(!) for 1 h - but noone can start or join a game/server anymore.

Greetings from Germany
VEX-Clan
Ben / Kamikazi


P.S.: You are doing a great job so now it's possible to find new MP-players. Good luck for future projects.

**Comment by roncli** [comment]
Please copy and paste your appsettings.json for your olproxy here, and I'll see if anything stands out.

**Comment by VEX-Ben** [comment]
Sorry, in this moment i checked you need the Answer here - I send it per @ but my mistake - her it is the appsettings.json from our server.

{
  "isServer": true,
  "signOff": true,
  "trackerBaseUrl": "https://olproxy.otl.gg",
  "serverName": "<VEX>Server_Use 'vex-server.de' as PW",
  "notes": "Europe, Germany, Use 'vex-server.de' as Password, Intel Xeon E5-2630, 8GB, 1GB NIC"
}

**Comment by VEX-Ben** [comment]
Hi Ronald,
   
  
  
   in this moment I saw that the list ist closed by mine - sorry don't know how I did this, it was not my intention because the "problem" is not done. HOw can I open it again or doesn't this matter?
   
  
  
   
  
  
   greetings from Aachen/Germany
  
  
   VEX-Ben
   
  
  
   "Ronald M. Clifford" <notifications@github.com> hat am 13. August 2019 um 04:44 geschrieben: 
   
   
   Please copy and paste your appsettings.json for your olproxy here, and I'll see if anything stands out.

**Comment by roncli** [comment]
Yes, that is all correct.  As long as you close olproxy normally and don't force quit it, it'll send the signoff properly.  If you force quit it, though, it doesn't close normally and your server will be stuck as showing online.

Future versions will remove the need for having to deal with olproxy, as we're trying to phase that out.

**Comment by roncli** [comment]
Closing this, as it will be fixed in #12.
